name: build runtime

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc python3

    - name: build runtime (linux)
      run: |
        python3 ./build.py -b
        cp ivra.elf ivra-linux-x86_64.elf
    
    - name: build runtime (profanOS)
      run: |
        git clone https://github.com/elydre/ivra.git
        cd ivra
        python3 ./build.py -b
        cp ivra.bin ../ivra-profanOS.bin

    - name: Release to GitHub
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: ivra latest runtime
        automatic_release_tag: latest
        repo_token: "${{ secrets.GIT_TOKEN }}"
        files: |
          ivra-linux-x86_64.elf
          ivra-profanOS.bin
